# Generated by Django 3.1.7 on 2021-03-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='core.couriertype'),
        ),
        migrations.AlterField(
            model_name='courierregion',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_regions', to='core.courier'),
        ),
        migrations.AlterField(
            model_name='courierregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_regions', to='core.region'),
        ),
        migrations.AlterField(
            model_name='courierworkshift',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_shifts', to='core.courier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.region'),
        ),
        migrations.AlterField(
            model_name='orderdeliveryinterval',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_intervals', to='core.order'),
        ),
    ]
