# Generated by Django 3.1.7 on 2021-03-14 12:30

from django.db import migrations


def fill_in_courier_type(apps, schema_editor):
    CourierType = apps.get_model('core', 'CourierType')
    CourierType.objects.get_or_create(code='foot', defaults={'capacity': 10})
    CourierType.objects.get_or_create(code='bike', defaults={'capacity': 15})
    CourierType.objects.get_or_create(code='car', defaults={'capacity': 50})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210314_1054'),
    ]

    operations = [
        migrations.RunPython(fill_in_courier_type)
    ]
