# Generated by Django 3.1.7 on 2021-03-20 17:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210319_1958'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='complete_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
