# Can be generated by django.core.management.utils.get_random_secret_key
SECRET_KEY = 'h@%87mduo&qek+88kqksuko*!_j437nm)eip*e4kox^d2qn08y'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'candy_shop',
        'USER': 'candy_shop',
        'PASSWORD': 'candy_shop',  # Insert your password here
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}

ALLOWED_HOSTS = ['0.0.0.0']  # Add IP or domain name of the server
